/**
 * Policy page templates for Terms of Service and Privacy Policy.
 * Called by SetupService.completeSetup() to seed draft policy pages for new installs.
 * The generated pages are in draft status — the owner must review and publish them.
 */

export interface PolicyParams {
  siteName: string;
  siteUrl: string;
  contactEmail: string;
  ownerName: string;
  effectiveDate: string; // e.g. "June 26, 2026"
}

// Wrap a TipTap doc inside the page editor's sections envelope
function sectionsWrap(doc: object): object {
  const uid = () => Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);
  return {
    type: 'sections',
    sections: [{
      id: uid(),
      columns: 1,
      zones: [{ id: uid(), span: 1, content: doc }],
    }],
  };
}

// TipTap JSON node builders
const p = (text: string) => ({
  type: 'paragraph',
  content: [{ type: 'text', text }],
});
const h2 = (text: string) => ({
  type: 'heading',
  attrs: { level: 2 },
  content: [{ type: 'text', text }],
});
const li = (text: string) => ({
  type: 'listItem',
  content: [{ type: 'paragraph', content: [{ type: 'text', text }] }],
});
const ul = (...items: string[]) => ({
  type: 'bulletList',
  content: items.map(li),
});
const draftBanner = (docTitle: string) => ({
  type: 'paragraph',
  content: [{
    type: 'text',
    marks: [{ type: 'bold' }],
    text: `⚠️ DRAFT — This ${docTitle} was automatically generated by the AECMS setup wizard. ` +
      `You must review this document carefully before publishing it, and you should consult ` +
      `a qualified legal professional to ensure it covers your specific situation. ` +
      `To publish: Admin → Pages → change status from Draft to Published.`,
  }],
});

export function buildTermsContent(p_: PolicyParams): string {
  const { siteName, siteUrl, contactEmail, ownerName, effectiveDate } = p_;
  const doc = {
    type: 'doc',
    content: [
      draftBanner('Terms of Service'),
      h2('Terms of Service'),
      p(`Effective date: ${effectiveDate}`),
      p(`Please read these Terms of Service carefully before using ${siteName} (the "Service") operated by ${ownerName} ("we," "us," or "our") at ${siteUrl}.`),
      p(`By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of these Terms, you may not use the Service.`),

      h2('1. Use of the Service'),
      p(`${siteName} is a content and commerce platform. You may use the Service for lawful personal and non-commercial purposes. You agree not to:`),
      ul(
        'Use the Service in any way that violates applicable law or regulation.',
        'Attempt to gain unauthorised access to any part of the Service or its related systems.',
        'Upload or transmit any content that is unlawful, harmful, abusive, defamatory, or infringing of third-party rights.',
        'Use automated means to scrape, crawl, or harvest data from the Service without our prior written consent.',
        'Impersonate any person or entity or misrepresent your affiliation with any person or entity.',
      ),

      h2('2. User Accounts'),
      p(`When you create an account, you must provide accurate and complete information. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. Notify us immediately at ${contactEmail} if you believe your account has been compromised.`),
      p(`We reserve the right to terminate or suspend accounts that violate these Terms, at our sole discretion and without prior notice.`),

      h2('3. Purchases and Payments'),
      p(`All prices are displayed in US dollars. Payments are processed by Stripe and/or PayPal. By completing a purchase you authorise the applicable processor to charge the payment method you provide.`),
      p(`We reserve the right to modify pricing at any time. Price changes do not apply retroactively to completed orders.`),
      p(`All sales are final unless otherwise stated at the point of purchase. See Section 4 for digital products.`),

      h2('4. Digital Products'),
      p(`Digital products (ebooks, downloadable files, online content) are delivered electronically after payment confirmation. Due to the nature of digital goods:`),
      ul(
        'All digital product sales are final — no refunds are offered once a download link has been issued.',
        'Download links are time-limited and intended for personal use only. Do not share links.',
        'We may replace defective or corrupted files; contact us at ' + contactEmail + ' if you experience a download problem.',
      ),
      p(`You receive a non-exclusive, non-transferable licence to use digital purchases for personal, non-commercial purposes. You may not reproduce, distribute, or create derivative works without our express written permission.`),

      h2('5. Intellectual Property'),
      p(`All content published on ${siteName} — including articles, images, product descriptions, and code — is the property of ${ownerName} or its content contributors and is protected by copyright and other intellectual property laws.`),
      p(`Nothing in these Terms grants you any right to use our trademarks, logos, or other proprietary designations without prior written consent.`),

      h2('6. Third-Party Links'),
      p(`The Service may contain links to third-party websites or services. We are not responsible for the content or practices of any linked site and do not endorse them. Visiting any third-party link is at your own risk.`),

      h2('7. Disclaimer of Warranties'),
      p(`The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.`),
      p(`We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components.`),

      h2('8. Limitation of Liability'),
      p(`To the fullest extent permitted by applicable law, ${ownerName} shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of or inability to use the Service, even if we have been advised of the possibility of such damages.`),
      p(`Our total liability to you for any claim arising from or relating to these Terms or the Service shall not exceed the amount you paid us in the twelve (12) months preceding the claim.`),

      h2('9. Governing Law'),
      p(`These Terms are governed by and construed in accordance with the laws of the State of Texas, United States, without regard to its conflict of law provisions. Any dispute arising under these Terms shall be resolved in the courts located in Texas.`),

      h2('10. Changes to These Terms'),
      p(`We may update these Terms from time to time. When we do, we will revise the effective date at the top of this page. Continued use of the Service after any changes constitutes your acceptance of the new Terms.`),

      h2('11. Contact'),
      p(`Questions about these Terms? Contact us at ${contactEmail}.`),
    ],
  };
  return JSON.stringify(sectionsWrap(doc));
}

export function buildPrivacyContent(p_: PolicyParams): string {
  const { siteName, siteUrl, contactEmail, ownerName, effectiveDate } = p_;
  const doc = {
    type: 'doc',
    content: [
      draftBanner('Privacy Policy'),
      h2('Privacy Policy'),
      p(`Effective date: ${effectiveDate}`),
      p(`${ownerName} operates ${siteName} at ${siteUrl}. This Privacy Policy explains how we collect, use, and protect your personal information when you use our Service.`),

      h2('1. Information We Collect'),
      p(`We collect the following categories of information:`),
      ul(
        'Account information: email address, username, first and last name (provided at registration or checkout).',
        'Order and payment information: items purchased, order total, shipping address. We do not store payment card numbers — these are handled directly by Stripe and PayPal.',
        'Communications: messages you send us via email or contact forms.',
        'Technical data: IP address, browser type, pages visited, and timestamps collected automatically when you use the Service.',
      ),

      h2('2. How We Use Your Information'),
      p(`We use the information we collect to:`),
      ul(
        'Fulfil orders and deliver digital or physical products.',
        'Send transactional emails: order confirmations, download links, and email verification.',
        'Personalise purchased digital files with your name, if that feature is enabled.',
        'Respond to support enquiries.',
        'Improve and secure the Service.',
        'Comply with legal obligations.',
      ),
      p(`We do not sell your personal information to third parties. We do not use your information for advertising purposes.`),

      h2('3. Payment Processing'),
      p(`Payments are processed by Stripe, Inc. and/or PayPal Holdings, Inc. When you make a purchase, you submit payment details directly to those processors through their secure interfaces. ${siteName} does not receive or store card numbers, CVV codes, or bank account details.`),
      p(`Stripe's privacy policy is available at https://stripe.com/privacy. PayPal's privacy policy is available at https://www.paypal.com/webapps/mpp/ua/privacy-full.`),

      h2('4. Cookies and Local Storage'),
      p(`The Service uses browser local storage (not traditional cookies) to maintain your session and shopping cart. This data remains on your device and is not transmitted to third parties.`),
      p(`We do not use tracking cookies, advertising pixels, or third-party analytics services.`),

      h2('5. Data Retention'),
      p(`We retain account information for as long as your account is active. Order records are retained for a minimum of seven (7) years to comply with tax and accounting requirements. You may request deletion of your account at any time (see Section 7); order records required for legal compliance will be retained even after account deletion.`),

      h2('6. Data Security'),
      p(`We take reasonable technical and organisational measures to protect your personal information, including encryption of stored credentials and sensitive settings. No method of transmission over the internet is 100% secure; we cannot guarantee absolute security.`),

      h2('7. Your Rights'),
      p(`Depending on your jurisdiction, you may have the right to:`),
      ul(
        'Access the personal information we hold about you.',
        'Correct inaccurate information.',
        'Request deletion of your account and associated personal data (subject to retention requirements).',
        'Object to or restrict certain processing.',
        'Receive a portable copy of your data.',
      ),
      p(`To exercise any of these rights, contact us at ${contactEmail}. We will respond within a reasonable timeframe.`),
      p(`You can delete your own account at any time from your Account page.`),

      h2('8. Third-Party Services'),
      p(`Beyond payment processors, the Service may use:`),
      ul(
        'Cloudflare Turnstile — privacy-preserving CAPTCHA on the registration form. No personally identifiable information is shared with Cloudflare beyond what is standard in an HTTP request.',
        'Cloud storage providers (Google Cloud Storage, AWS S3, or similar) — used to store uploaded media and digital product files. Your files are not made available to the provider for any purpose other than storage.',
      ),

      h2('9. Children\'s Privacy'),
      p(`The Service is not directed at children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, contact us at ${contactEmail} and we will delete it promptly.`),

      h2('10. Changes to This Policy'),
      p(`We may update this Privacy Policy from time to time. We will notify you of significant changes by updating the effective date at the top of this page. Continued use of the Service after changes constitutes acceptance of the revised Policy.`),

      h2('11. Contact'),
      p(`Questions about this Privacy Policy or your personal data? Contact us at ${contactEmail}.`),
      p(`${ownerName}`),
      p(siteUrl),
    ],
  };
  return JSON.stringify(sectionsWrap(doc));
}
